import {Routes,Route,Navigate} from 'react-router-dom';import Layout from './layouts/Layout';import Landing from './pages/Landing';
import {SignIn,SignUp} from './pages/Auth';import {useAuth} from './auth';
import {StudentHome,StudentGaps,GapAnalysis,LearningPath,Quizzes,QuizPage,Progress} from './pages/student';
import {TeacherHome,TeacherStudents,StudentAnalysis,TeacherGaps,Materials,Reports,TeacherAssessments} from './pages/teacher';
function ProtectedLayout({role}){const {user,ready}=useAuth();if(!ready)return <div className="p-8 text-center text-slate-500">Checking your session…</div>;if(!user)return <Navigate to={`/login?role=${role}`} replace/>;if(user.role!==role)return <Navigate to={user.role==='teacher'?'/teacher/dashboard':'/student/dashboard'} replace/>;return <Layout role={role}/>}

export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<SignIn/>}/><Route path="/signup" element={<SignUp/>}/>
 <Route path="/student" element={<ProtectedLayout role="student"/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<StudentHome/>}/><Route path="gaps" element={<StudentGaps/>}/><Route path="gaps/:id" element={<GapAnalysis/>}/><Route path="learning-path" element={<LearningPath/>}/><Route path="quizzes" element={<Quizzes/>}/><Route path="quiz/:id" element={<QuizPage/>}/><Route path="progress" element={<Progress/>}/></Route>
 <Route path="/teacher" element={<ProtectedLayout role="teacher"/>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<TeacherHome/>}/><Route path="assessments" element={<TeacherAssessments/>}/><Route path="students" element={<TeacherStudents/>}/><Route path="students/:id" element={<StudentAnalysis/>}/><Route path="gaps" element={<TeacherGaps/>}/><Route path="materials" element={<Materials/>}/><Route path="reports" element={<Reports/>}/></Route>
 <Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
