import {Button} from '../components/ui';import {ArrowDown,Search,Network,Route,Users,TrendingUp} from 'lucide-react';
const flow=['Student answer','AI analysis','Concept detection','Knowledge graph','Learning gap','Personalized recommendation'];
const feats=[[Search,'Detect learning gaps','Find the exact concepts each student is missing, not just a low score.'],[Network,'Understand why students struggle','Trace gaps back to missing prerequisite concepts.'],[Route,'Personalized learning paths','A step-by-step route that starts where the student actually is.'],[Users,'Teacher insights','See class-wide weak spots and review the AI’s findings.'],[TrendingUp,'Continuous improvement','Every quiz updates mastery so progress stays visible.']];
export default function Landing(){return <div className="min-h-screen">
 <section className="mx-auto max-w-5xl px-6 pb-16 pt-20 text-center"><h1 className="font-display text-4xl sm:text-6xl leading-tight">Personalized Learning. Powered by Understanding.</h1>
 <p className="mx-auto mt-6 max-w-2xl text-lg text-slate-600">In a class of 60, no teacher can see every misunderstanding. This platform reads student answers, finds the concepts behind the mistakes, and builds a path to fix them.</p>
 <div className="mt-8 flex flex-wrap justify-center gap-3"><Button to="/student/dashboard" className="px-6 py-3">Continue as Student</Button><Button to="/teacher/dashboard" variant="ghost" className="px-6 py-3">Continue as Teacher</Button></div></section>
 <section className="mx-auto max-w-md px-6 pb-16" aria-label="How it works"><ol className="flex flex-col items-center gap-1">{flow.map((f,i)=><li key={f} className="flex flex-col items-center"><div className={`rounded-xl border px-6 py-3 text-sm font-semibold ${i===4?'border-bad bg-red-50 text-bad':i===5?'border-good bg-emerald-50 text-good':'border-line bg-white'}`}>{f}</div>{i<5&&<ArrowDown size={18} className="my-1 text-slate-400" aria-hidden/>}</li>)}</ol></section>
 <section className="mx-auto grid max-w-5xl gap-4 px-6 pb-20 sm:grid-cols-2 lg:grid-cols-3">{feats.map(([I,t,d])=><div key={t} className="card p-6"><I className="text-brand-600" aria-hidden/><h2 className="mt-3 font-semibold">{t}</h2><p className="mt-1 text-sm text-slate-600">{d}</p></div>)}</section></div>}
