import {Link} from 'react-router-dom';
import {ArrowRight,BarChart3,BookOpenCheck,Brain,Check,GraduationCap,LockKeyhole,Sparkles,Target,UserRound} from 'lucide-react';
import {useAuth} from '../auth';

const steps=[['01','Create an assessment','Teachers add a Python question and the concepts students should demonstrate.'],['02','Explain your thinking','Students write an answer in their own words.'],['03','See what to review','The analyzer highlights matched concepts and possible gaps.']];
const features=[[Target,'Concept-level feedback','See which ideas appear in an answer and which may need more practice.'],[LockKeyhole,'Separate student and teacher spaces','Each account has a role and access to the tools for that role.'],[BarChart3,'Track assessment attempts','Review saved student answers and keyword analysis in the teacher workspace.']];

export default function Landing(){
 const {user,logout}=useAuth();
 const dashboard=user?(user.role==='teacher'?'/teacher/dashboard':'/student/dashboard'):'';
 return <div className="min-h-screen overflow-hidden bg-[#f7f8fc] text-ink">
  <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link to="/" className="flex items-center gap-2 font-display text-lg"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-brand-600 text-white"><Brain size={22}/></span>Learning Gap Analyzer</Link>
   <nav className="flex items-center gap-2">{user?<><span className="hidden text-sm text-slate-600 sm:inline">Hi, {user.name}</span><Link to={dashboard} className="btn border border-line bg-white">Open workspace<ArrowRight size={15}/></Link><button onClick={logout} className="btn text-slate-600 hover:bg-white">Log out</button></>:<><Link to="/login" className="btn text-slate-700 hover:bg-white">Sign in</Link><Link to="/signup" className="btn bg-brand-600 text-white hover:bg-brand-700">Create account</Link></>}</nav>
  </header>
  <main>
   <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-10 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:pb-28 lg:pt-16">
    <div className="pointer-events-none absolute -left-40 top-0 h-96 w-96 rounded-full bg-indigo-200/40 blur-3xl"/>
    <div className="relative"><div className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-white/80 px-3 py-1.5 text-xs font-semibold text-brand-700 shadow-sm"><Sparkles size={14}/>A clearer way to close learning gaps</div>
     <h1 className="mt-6 max-w-3xl font-display text-5xl leading-[1.08] tracking-tight sm:text-6xl">Understand the answer.<br/><span className="text-brand-600">Find the next step.</span></h1>
     <p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">A Python Fundamentals workspace where teachers create short assessments and students get a useful view of the concepts their answers demonstrate.</p>
     <div className="mt-8 flex flex-wrap gap-3"><Link to={user?dashboard:'/signup?role=student'} className="btn gap-2 bg-brand-600 px-5 py-3 text-white shadow-lg shadow-indigo-200 hover:bg-brand-700">{user?'Go to your workspace':'Get started'}<ArrowRight size={17}/></Link><a href="#how-it-works" className="btn border border-line bg-white px-5 py-3 text-slate-700">How it works</a></div>
     <div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-600"><span className="flex items-center gap-2"><Check size={16} className="text-good"/>Teacher and student accounts</span><span className="flex items-center gap-2"><Check size={16} className="text-good"/>Saved assessment feedback</span></div>
    </div>
    <div className="relative mx-auto w-full max-w-lg"><div className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-amber-200/60 blur-2xl"/><div className="absolute -bottom-8 -left-8 h-32 w-32 rounded-full bg-indigo-300/50 blur-2xl"/>
     <div className="relative rounded-[2rem] border border-white bg-gradient-to-br from-indigo-100 via-white to-sky-100 p-4 shadow-2xl shadow-indigo-200/50 sm:p-6"><div className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-brand-600">Python fundamentals</p><h2 className="mt-2 font-display text-xl">A better signal than a score</h2></div><span className="grid h-11 w-11 place-items-center rounded-2xl bg-indigo-50 text-brand-600"><BookOpenCheck/></span></div>
      <div className="mt-6 rounded-2xl bg-[#f7f8fc] p-4"><p className="text-xs font-semibold text-slate-500">STUDENT ANSWER</p><p className="mt-2 text-sm leading-6 text-slate-700">“A function is a reusable block. It can take parameters and return a result.”</p></div>
      <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><p className="flex items-center gap-2 text-xs font-semibold text-emerald-800"><Check size={14}/>CONCEPTS SHOWN</p><div className="mt-3 space-y-2 text-sm text-emerald-900"><p>Functions</p><p>Parameters</p></div></div><div className="rounded-2xl border border-amber-100 bg-amber-50/70 p-4"><p className="flex items-center gap-2 text-xs font-semibold text-amber-800"><Target size={14}/>REVIEW NEXT</p><p className="mt-3 text-sm text-amber-950">Practice tracing a function’s return value.</p></div></div>
      <div className="mt-4 flex items-center gap-3 rounded-2xl border border-line p-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><BarChart3 size={20}/></span><div><p className="text-sm font-semibold">Feedback tied to concepts</p><p className="text-xs text-slate-500">Start small. Build toward deeper analysis.</p></div></div>
     </div></div>
    </div>
   </section>
   <section id="how-it-works" className="border-y border-slate-200/80 bg-white py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[.16em] text-brand-600">Simple by design</p><h2 className="mt-3 font-display text-3xl sm:text-4xl">From a written answer to a useful next step</h2><p className="mt-3 text-slate-600">A focused first version for Python Fundamentals, built around teacher-created questions and student explanations.</p></div>
    <div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(([number,title,body])=><article key={number} className="rounded-3xl border border-line bg-[#fbfcff] p-6"><span className="font-display text-3xl text-brand-300">{number}</span><h3 className="mt-5 font-display text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div>
   </div></section>
   <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-brand-600">Built for both sides</p><h2 className="mt-3 font-display text-3xl sm:text-4xl">The right tools for every role</h2></div><div className="grid gap-4 sm:grid-cols-3">{features.map(([Icon,title,body])=><article key={title} className="rounded-3xl border border-line bg-white p-5 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-600"><Icon size={21}/></span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></article>)}</div></div>
    {!user&&<div className="mt-12 grid gap-4 sm:grid-cols-2"><Link to="/signup?role=student" className="group flex items-center justify-between rounded-3xl bg-brand-700 p-6 text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5"><span className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><GraduationCap/></span><span><b className="block text-lg">I’m a student</b><span className="text-sm text-indigo-100">Practice and review your answers</span></span></span><ArrowRight className="transition group-hover:translate-x-1"/></Link><Link to="/signup?role=teacher" className="group flex items-center justify-between rounded-3xl border border-line bg-white p-6 shadow-sm transition hover:-translate-y-0.5"><span className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-50 text-amber-700"><UserRound/></span><span><b className="block text-lg">I’m a teacher</b><span className="text-sm text-slate-500">Create assessments and review answers</span></span></span><ArrowRight className="text-brand-600 transition group-hover:translate-x-1"/></Link></div>}
   </section>
  </main>
  <footer className="border-t border-slate-200 bg-white px-5 py-6 text-center text-xs text-slate-500">Learning Gap Analyzer · Python Fundamentals milestone</footer>
 </div>
}
