import {useEffect,useState} from 'react';import {useParams} from 'react-router-dom';
import {LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from 'recharts';
import {Gauge,CheckCircle2,AlertTriangle,Flame,Check,Circle,ArrowRight,Clock} from 'lucide-react';
import {StatCard,PageHead,Button,Tabs,ChartCard,ProgressBar,EmptyState} from '../components/ui';
import GapCard from '../components/GapCard';import RecommendationCard from '../components/RecommendationCard';import ConceptGraph from '../components/ConceptGraph';
import {gaps,graph,graphs,path} from '../data/concepts';import {trend,activity,quizScores} from '../data/analytics';import {recs} from '../data/recommendations';
import {api} from '../api';
import {useAuth} from '../auth';
const TrendChart=({title})=><ChartCard title={title} sub="Competency % over the last 6 weeks"><LineChart data={trend}><CartesianGrid stroke="#E3E6EC" vertical={false}/><XAxis dataKey="w"/><YAxis domain={[40,100]}/><Tooltip/><Line dataKey="v" name="Competency" stroke="#2F4FA8" strokeWidth={3} dot/></LineChart></ChartCard>;
export function StudentHome(){const {user}=useAuth();const [assigned,setAssigned]=useState([]);const [assignmentError,setAssignmentError]=useState('');
 useEffect(()=>{api('/student/assignments').then(data=>setAssigned(data.assignments||[])).catch(e=>setAssignmentError(e.message))},[]);
 const average=assigned.length?Math.round(assigned.reduce((sum,item)=>sum+item.progress_percent,0)/assigned.length):0;
 const assessmentCount=assigned.reduce((sum,item)=>sum+item.assessment_count,0);const submissionCount=assigned.reduce((sum,item)=>sum+item.submission_count,0);
 return <>
 <PageHead title={`Welcome, ${user?.name||'Student'}`} sub="Your assigned subjects and assessment progress."/>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Average assessment coverage" value={`${average}%`} icon={Gauge}/><StatCard label="Assigned subjects" value={assigned.length} icon={CheckCircle2}/><StatCard label="Available assessments" value={assessmentCount} icon={AlertTriangle}/><StatCard label="Submitted answers" value={submissionCount} icon={Flame}/></div>
 {assignmentError&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-bad">{assignmentError}</p>}
 <h2 className="mb-3 mt-8 font-display text-xl">My subjects</h2>{assigned.length?<div className="grid gap-4 md:grid-cols-2">{assigned.map(item=><article key={item.assignment_id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{item.subject}</h3><p className="mt-1 text-sm text-slate-500">Teacher: {item.teacher_name}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status==='active'?'bg-emerald-50 text-good':'bg-amber-50 text-warn'}`}>{item.status}</span></div><div className="mt-4 flex justify-between text-sm"><span>Assessment coverage</span><b>{item.progress_percent}%</b></div><div className="mt-2"><ProgressBar value={item.progress_percent}/></div><p className="mt-2 text-xs text-slate-500">{item.submission_count} of {item.assessment_count} assessment attempts submitted</p><Button to="/student/quizzes" variant="ghost" className="mt-4">Open assessments</Button></article>)}</div>:<EmptyState text="No subjects assigned yet. Ask your teacher to assign your registered email address."/>}
 <div className="mt-6"><TrendChart title="Learning progress"/></div>
 <h2 className="mb-3 mt-8 font-display text-xl">Priority learning gaps</h2><div className="grid gap-4 md:grid-cols-3">{[...gaps].sort((a,b)=>a.mastery-b.mastery).slice(0,3).map(g=><GapCard key={g.id} g={{...g,why:g.why.slice(0,80)+'…'}}/>)}</div>
 <h2 className="mb-3 mt-8 font-display text-xl">Recommended learning</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recs.map(r=><RecommendationCard key={r.title} r={r}/>)}</div></>}
export function StudentGaps(){const [f,setF]=useState('All');const list=gaps.filter(g=>f==='All'||f.startsWith(g.severity));
 return <><PageHead title="My Learning Gaps" sub="These concepts are currently limiting your progress."/><Tabs tabs={['All','High Priority','Medium Priority','Low Priority']} value={f} onChange={setF}/>
 <div className="mt-5 grid gap-4 md:grid-cols-2">{list.length?list.map(g=><GapCard key={g.id} g={g} detailed/>):<EmptyState text="No gaps in this category."/>}</div></>}
export function GapAnalysis(){const {id}=useParams();const g=gaps.find(x=>x.id===id)||gaps[0];const nodes=graphs[g.id]||[{name:'Fundamentals',state:'known'},{name:g.prereq,state:'gap'},{name:g.name,state:'gap'}];
 return <><PageHead title={g.name} sub="Detailed gap analysis"/>
 <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Current mastery" value={`${g.mastery}%`}/><StatCard label="Target mastery" value="80%"/><StatCard label="Gap severity" value={g.severity}/></div>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">What you know</h2><ul className="mt-3 space-y-2 text-sm">{nodes.filter(n=>n.state==='known').map(n=><li key={n.name} className="flex gap-2 text-good"><Check size={16}/>{n.name}</li>)}</ul></section>
 <section className="card p-5"><h2 className="font-semibold">What you’re missing</h2><ul className="mt-3 space-y-2 text-sm">{nodes.filter(n=>n.state==='gap').map(n=><li key={n.name} className="flex gap-2 text-bad"><AlertTriangle size={16}/>{n.name}</li>)}</ul></section></div>
 <section className="card mt-6 p-5"><h2 className="mb-4 font-semibold">Prerequisite map</h2><div className="overflow-x-auto"><ConceptGraph nodes={nodes}/></div></section>
 <section className="card mt-6 p-5"><h2 className="mb-3 font-semibold">Evidence from your answers</h2><div className="space-y-3">{g.evidence.map(e=><blockquote key={e.q} className="rounded-xl bg-paper p-4 text-sm"><p className="text-slate-500">{e.q}</p><p className="mt-1 font-medium">{e.a}</p><p className="mt-1 text-bad">Why it’s weak: {e.note}</p></blockquote>)}</div></section>
 <section className="card mt-6 p-5"><h2 className="font-semibold">Recommended next steps</h2><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm">{[`Review ${g.prereq.toLowerCase()}`,`Learn ${g.name.toLowerCase()}`,'Take a 5-question quiz','Reassess mastery'].map(x=><li key={x}>{x}</li>)}</ol><Button to="/student/learning-path" className="mt-4">Start personalized learning</Button></section></>}
export function LearningPath(){const st={Done:'border-good bg-emerald-50',Current:'border-brand-500 bg-brand-50 shadow-md',Next:'border-line bg-white'};
 return <><PageHead title="Learning Path" sub="Your route through Python Fundamentals."/><ol className="mx-auto max-w-xl">{path.map((p,i)=><li key={p.name} className="flex flex-col items-center">
 <div className={`w-full rounded-2xl border-2 p-5 ${st[p.status]}`}><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-semibold">{p.status==='Done'?<Check className="text-good" size={18}/>:p.status==='Current'?<ArrowRight className="text-brand-600" size={18}/>:<Circle size={16}/>}{p.name}</span><span className="text-xs font-semibold uppercase">{p.status}</span></div>
 <div className="mt-3 flex items-center gap-3 text-xs text-slate-600"><span className="w-20">Mastery {p.mastery}%</span><ProgressBar value={p.mastery}/><span className="flex shrink-0 items-center gap-1"><Clock size={12}/>{p.time}</span></div>
 {p.status!=='Done'&&<Button to="/student/quizzes" className="mt-3" variant={p.status==='Current'?'primary':'ghost'}>Browse assessments</Button>}</div>{i<path.length-1&&<div className="h-6 w-0.5 bg-line"/>}</li>)}</ol></>}
export function Quizzes(){const [items,setItems]=useState([]);const [assigned,setAssigned]=useState([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([api('/assessments'),api('/student/assignments')]).then(([assessments,subjects])=>{setItems(assessments.assessments||[]);setAssigned(subjects.assignments||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 return <><PageHead title="Python Assessments" sub="Write an answer and review which Python concepts it demonstrates."/>
 {loading&&<EmptyState text="Loading assessments…"/>}{error&&<div role="alert" className="card p-5 text-bad">{error}. Start the FastAPI backend and confirm MongoDB is connected, then refresh.</div>}
 {assigned.length>0&&<section className="mb-6"><h2 className="mb-3 font-display text-xl">Your assigned subjects</h2><div className="flex flex-wrap gap-2">{assigned.map(item=><span key={item.assignment_id} className="rounded-full border border-line bg-white px-3 py-1.5 text-sm"><b>{item.subject}</b><span className="ml-2 text-slate-500">by {item.teacher_name}</span></span>)}</div></section>}
 {!loading&&!error&&!items.length&&<EmptyState text="No assessments yet. Ask your teacher to create one from the teacher demo."/>}
 <div className="grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.assessment_id} className="card p-5"><p className="text-xs font-semibold uppercase text-brand-600">{item.subject}</p><h2 className="mt-2 font-semibold">{item.title}</h2><p className="mt-1 text-sm text-slate-600">{item.description||'Practice Python and identify concepts to review.'}</p><p className="mt-3 text-xs text-slate-500">{item.question_count} written question</p><Button to={`/student/quiz/${item.assessment_id}`} className="mt-4">Start assessment</Button></article>)}</div></>}

export function Progress(){return <><PageHead title="Progress" sub="You’ve closed 3 gaps this month."/>
 <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Learning streak" value="7 days" icon={Flame}/><StatCard label="Gaps closed" value="3" icon={CheckCircle2}/><StatCard label="Avg quiz score" value="78%" icon={Gauge}/></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-2"><TrendChart title="Competency trend"/>
 <ChartCard title="Concept mastery" sub="Your weakest concepts"><BarChart data={gaps} layout="vertical"><CartesianGrid stroke="#E3E6EC" horizontal={false}/><XAxis type="number" domain={[0,100]}/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="mastery" fill="#2F4FA8" radius={6}/></BarChart></ChartCard>
 <ChartCard title="Quiz performance" sub="Recent scores %"><LineChart data={quizScores}><XAxis dataKey="q"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="v" stroke="#B45309" strokeWidth={3}/></LineChart></ChartCard>
 <ChartCard title="Weekly activity" sub="Minutes studied"><BarChart data={activity}><XAxis dataKey="d"/><YAxis/><Tooltip/><Bar dataKey="m" fill="#0F7B53" radius={6}/></BarChart></ChartCard></div></>}

export function QuizPage(){const {id}=useParams();const [assessment,setAssessment]=useState(null);const [answer,setAnswer]=useState('');const [result,setResult]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 useEffect(()=>{api(`/assessments/${id}`).then(setAssessment).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{const data=await api(`/assessments/${id}/submissions`,{method:'POST',body:JSON.stringify({answer})});setResult(data)}catch(e){setError(e.message)}finally{setSaving(false)}}
 if(loading)return <EmptyState text="Loading assessment…"/>;if(!assessment)return <div><PageHead title="Assessment unavailable"/><div role="alert" className="card p-5 text-bad">{error}</div><Button to="/student/quizzes" className="mt-4">Back to assessments</Button></div>;
 return <div className="mx-auto max-w-2xl"><PageHead title={assessment.title} sub={assessment.subject}/>
 {!result?<form onSubmit={submit}><section className="card p-6"><p className="font-semibold">{assessment.question}</p><label className="mt-5 block text-sm font-medium">Your answer<textarea required minLength={3} maxLength={10000} rows={7} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain your answer in your own words…" className="mt-2 w-full rounded-xl border border-line bg-white px-3 py-3 text-sm"/></label><p className="mt-2 text-xs text-slate-500">Your answer is saved to the project database for this demo.</p></section>{error&&<p role="alert" className="mt-3 text-sm text-bad">{error}</p>}<Button type="submit" disabled={saving} className="mt-4">{saving?'Analyzing…':'Submit answer'}</Button></form>:<><section className="card p-6"><p className="text-sm text-slate-500">Concept coverage</p><p className="mt-1 font-display text-5xl text-brand-600">{result.coverage_percent}%</p><p className="mt-2 text-sm">Saved answer · {new Date(result.created_at).toLocaleString()}</p><p className="mt-2 text-xs text-slate-500">Analysis: {result.analysis_status==='semantic_v2'?'semantic language model':'keyword fallback'}</p></section>
 <section className="card mt-4 p-5"><h2 className="mb-4 font-semibold">Concept-by-concept feedback</h2><div className="space-y-4">{(result.concept_scores||[]).map(concept=><article key={concept.name}><div className="flex flex-wrap items-center justify-between gap-2"><b>{concept.name}</b><span className={`text-sm font-semibold ${concept.state==='known'?'text-good':'text-bad'}`}>{concept.mastery}% · {concept.state==='known'?'demonstrated':'review this concept'}</span></div><ProgressBar value={concept.mastery} color={concept.state==='known'?'bg-good':'bg-bad'}/>{concept.best_sentence&&<p className="mt-1 text-xs text-slate-500">Evidence: “{concept.best_sentence}” · matched by {concept.matched_by}</p>}</article>)}</div></section>
 {result.concept_graph?.length>0&&<section className="card mt-4 overflow-x-auto p-5"><h2 className="mb-4 font-semibold">Concept map</h2><ConceptGraph nodes={result.concept_graph}/></section>}
 <p className="mt-4 text-xs text-slate-500">Semantic scores are an early model estimate. Review the feedback alongside the written answer.</p><Button to="/student/quizzes" className="mt-4">Back to assessments</Button></>}
 </div>}
