import {useState} from 'react';import {Link,useParams,useNavigate,useLocation} from 'react-router-dom';
import {LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from 'recharts';
import {Gauge,CheckCircle2,AlertTriangle,Flame,Check,Circle,ArrowRight,Clock} from 'lucide-react';
import {StatCard,PageHead,Button,Tabs,ChartCard,ProgressBar,EmptyState} from '../components/ui';
import GapCard from '../components/GapCard';import RecommendationCard from '../components/RecommendationCard';import ConceptGraph from '../components/ConceptGraph';
import {gaps,graph,graphs,path} from '../data/concepts';import {trend,activity,quizScores} from '../data/analytics';import {recs} from '../data/recommendations';import {quizzes} from '../data/quizzes';
const TrendChart=({title})=><ChartCard title={title} sub="Competency % over the last 6 weeks"><LineChart data={trend}><CartesianGrid stroke="#E3E6EC" vertical={false}/><XAxis dataKey="w"/><YAxis domain={[40,100]}/><Tooltip/><Line dataKey="v" name="Competency" stroke="#2F4FA8" strokeWidth={3} dot/></LineChart></ChartCard>;
export function StudentHome(){return <>
 <PageHead title="Good morning, Alex" sub="Let’s close your learning gaps today."/>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Overall competency" value="72%" icon={Gauge}/><StatCard label="Concepts mastered" value="18" icon={CheckCircle2}/><StatCard label="Learning gaps" value="5" icon={AlertTriangle}/><StatCard label="Current streak" value="7 days" icon={Flame}/></div>
 <div className="mt-6"><TrendChart title="Learning progress"/></div>
 <h2 className="mb-3 mt-8 font-display text-xl">Priority learning gaps</h2><div className="grid gap-4 md:grid-cols-3">{[...gaps].sort((a,b)=>a.mastery-b.mastery).slice(0,3).map(g=><GapCard key={g.id} g={{...g,why:g.why.slice(0,80)+'…'}}/>)}</div>
 <h2 className="mb-3 mt-8 font-display text-xl">Recommended learning</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recs.map(r=><RecommendationCard key={r.title} r={r}/>)}</div></>}
export function StudentGaps(){const [f,setF]=useState('All');const list=gaps.filter(g=>f==='All'||f.startsWith(g.severity));
 return <><PageHead title="My Learning Gaps" sub="These concepts are currently limiting your progress."/><Tabs tabs={['All','High Priority','Medium Priority','Low Priority']} value={f} onChange={setF}/>
 <div className="mt-5 grid gap-4 md:grid-cols-2">{list.length?list.map(g=><GapCard key={g.id} g={g} detailed/>):<EmptyState text="No gaps in this category."/>}</div></>}
export function GapAnalysis(){const {id}=useParams();const g=gaps.find(x=>x.id===id)||gaps[0];const nodes=graphs[g.id]||[{name:'Fundamentals',state:'known'},{name:g.prereq,state:'gap'},{name:g.name,state:'gap'}];
 return <><PageHead title={g.name} sub="Detailed gap analysis"/>
 <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Current mastery" value={`${g.mastery}%`}/><StatCard label="Target mastery" value="80%"/><StatCard label="Gap severity" value={g.severity}/></div>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">What you know</h2><ul className="mt-3 space-y-2 text-sm">{nodes.filter(n=>n.state==='known').map(n=><li key={n.name} className="flex gap-2 text-good"><Check size={16}/>{n.name}</li>)}</ul></section>
 <section className="card p-5"><h2 className="font-semibold">What you’re missing</h2><ul className="mt-3 space-y-2 text-sm">{nodes.filter(n=>n.state==='gap').map(n=><li key={n.name} className="flex gap-2 text-bad"><AlertTriangle size={16}/>{n.name}</li>)}</ul></section></div>
 <section className="card mt-6 p-5"><h2 className="mb-4 font-semibold">Prerequisite map</h2><div className="overflow-x-auto"><ConceptGraph nodes={nodes}/></div></section>
 <section className="card mt-6 p-5"><h2 className="mb-3 font-semibold">Evidence from your answers</h2><div className="space-y-3">{g.evidence.map(e=><blockquote key={e.q} className="rounded-xl bg-paper p-4 text-sm"><p className="text-slate-500">{e.q}</p><p className="mt-1 font-medium">{e.a}</p><p className="mt-1 text-bad">Why it’s weak: {e.note}</p></blockquote>)}</div></section>
 <section className="card mt-6 p-5"><h2 className="font-semibold">Recommended next steps</h2><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm">{[`Review ${g.prereq.toLowerCase()}`,`Learn ${g.name.toLowerCase()}`,'Take a 5-question quiz','Reassess mastery'].map(x=><li key={x}>{x}</li>)}</ol><Button to="/student/learning-path" className="mt-4">Start personalized learning</Button></section></>}
export function LearningPath(){const st={Done:'border-good bg-emerald-50',Current:'border-brand-500 bg-brand-50 shadow-md',Next:'border-line bg-white'};
 return <><PageHead title="Learning Path" sub="Your route from foundations to Runtime Polymorphism."/><ol className="mx-auto max-w-xl">{path.map((p,i)=><li key={p.name} className="flex flex-col items-center">
 <div className={`w-full rounded-2xl border-2 p-5 ${st[p.status]}`}><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-semibold">{p.status==='Done'?<Check className="text-good" size={18}/>:p.status==='Current'?<ArrowRight className="text-brand-600" size={18}/>:<Circle size={16}/>}{p.name}</span><span className="text-xs font-semibold uppercase">{p.status}</span></div>
 <div className="mt-3 flex items-center gap-3 text-xs text-slate-600"><span className="w-20">Mastery {p.mastery}%</span><ProgressBar value={p.mastery}/><span className="flex shrink-0 items-center gap-1"><Clock size={12}/>{p.time}</span></div>
 {p.status!=='Done'&&<Button to="/student/quiz/q1" className="mt-3" variant={p.status==='Current'?'primary':'ghost'}>Start</Button>}</div>{i<path.length-1&&<div className="h-6 w-0.5 bg-line"/>}</li>)}</ol></>}
export function Quizzes(){const Sec=({t})=>{const l=quizzes.filter(q=>q.section===t);return <section className="mt-6"><h2 className="mb-3 font-display text-xl">{t==='Completed'?'Recently completed':t==='Recommended'?'Recommended for you':'Available quizzes'}</h2><div className="grid gap-4 md:grid-cols-2">{l.map(q=><article key={q.id} className="card p-5"><h3 className="font-semibold">{q.title}</h3><p className="text-sm text-slate-500">{q.concept}</p><p className="mt-2 text-xs text-slate-600">{q.questions.length} questions · {q.difficulty} · {q.time}</p>{q.score!==null&&<p className="mt-2 text-sm font-semibold text-good">Recent score: {q.score}%</p>}<Button to={`/student/quiz/${q.id}`} className="mt-3">{q.score!==null?'Retake quiz':'Start quiz'}</Button></article>)}</div></section>};
 return <><PageHead title="Quizzes" sub="Short checks that update your mastery."/><Sec t="Recommended"/><Sec t="Completed"/><Sec t="Available"/></>}

export function Progress(){return <><PageHead title="Progress" sub="You’ve closed 3 gaps this month."/>
 <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Learning streak" value="7 days" icon={Flame}/><StatCard label="Gaps closed" value="3" icon={CheckCircle2}/><StatCard label="Avg quiz score" value="78%" icon={Gauge}/></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-2"><TrendChart title="Competency trend"/>
 <ChartCard title="Concept mastery" sub="Your weakest concepts"><BarChart data={gaps} layout="vertical"><CartesianGrid stroke="#E3E6EC" horizontal={false}/><XAxis type="number" domain={[0,100]}/><YAxis type="category" dataKey="name" width={110}/><Tooltip/><Bar dataKey="mastery" fill="#2F4FA8" radius={6}/></BarChart></ChartCard>
 <ChartCard title="Quiz performance" sub="Recent scores %"><LineChart data={quizScores}><XAxis dataKey="q"/><YAxis domain={[0,100]}/><Tooltip/><Line dataKey="v" stroke="#B45309" strokeWidth={3}/></LineChart></ChartCard>
 <ChartCard title="Weekly activity" sub="Minutes studied"><BarChart data={activity}><XAxis dataKey="d"/><YAxis/><Tooltip/><Bar dataKey="m" fill="#0F7B53" radius={6}/></BarChart></ChartCard></div></>}

export function QuizPage(){const {id}=useParams();const nav=useNavigate();const quiz=quizzes.find(q=>q.id===id);const [i,setI]=useState(0);const [ans,setAns]=useState({});
 if(!quiz)return <EmptyState text="Quiz not found."/>;const qs=quiz.questions,q=qs[i];
 return <div className="mx-auto max-w-2xl"><PageHead title={quiz.title} sub={`Question ${i+1} of ${qs.length} · ${Object.keys(ans).length} answered`}/><ProgressBar value={(i+1)/qs.length*100}/>
 <nav aria-label="Question navigation" className="mt-4 flex flex-wrap gap-2">{qs.map((_,k)=><button key={k} aria-label={`Go to question ${k+1}`} aria-current={k===i} onClick={()=>setI(k)} className={`h-9 w-9 rounded-lg border text-sm font-semibold ${k===i?'border-brand-600 bg-brand-600 text-white':ans[k]!==undefined?'border-brand-500 bg-brand-50':'border-line bg-white'}`}>{k+1}</button>)}</nav>
 <fieldset className="card mt-5 p-6"><legend className="sr-only">Question {i+1}</legend><p className="font-semibold">{q.q}</p><div className="mt-4 space-y-2">{q.o.map((o,k)=><label key={o} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${ans[i]===k?'border-brand-500 bg-brand-50':'border-line hover:bg-paper'}`}><input type="radio" name="opt" checked={ans[i]===k} onChange={()=>setAns({...ans,[i]:k})}/>{o}</label>)}</div></fieldset>
 <div className="mt-4 flex justify-between"><Button variant="ghost" disabled={i===0} onClick={()=>setI(i-1)}>Previous</Button>{i<qs.length-1?<Button onClick={()=>setI(i+1)}>Next</Button>:<Button variant="good" onClick={()=>nav(`/student/quiz/${id}/results`,{state:{ans}})}>Submit quiz</Button>}</div></div>}
export function QuizResults(){const {id}=useParams();const {state}=useLocation();const quiz=quizzes.find(q=>q.id===id);
 if(!quiz||!state)return <div><EmptyState text="No results yet. Take the quiz first."/><Button to={`/student/quiz/${id}`} className="mt-4">Start quiz</Button></div>;
 const qs=quiz.questions,ans=state.ans,right=qs.filter((q,k)=>ans[k]===q.a).length,pct=Math.round(right/qs.length*100);
 const weak=[...new Set(qs.filter((q,k)=>ans[k]!==q.a).map(q=>q.c))],strong=[...new Set(qs.filter((q,k)=>ans[k]===q.a).map(q=>q.c))].filter(c=>!weak.includes(c));
 return <div className="mx-auto max-w-2xl"><PageHead title="Quiz results" sub={quiz.title}/><div className="card p-8 text-center"><p className="font-display text-6xl text-brand-600">{pct}%</p><p className="mt-2 text-sm">Score {right}/{qs.length} · Correct {right} · Incorrect {qs.length-right}</p></div>
 <div className="mt-4 grid gap-4 sm:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Needs improvement</h2><ul className="mt-2 list-disc pl-5 text-sm">{weak.length?weak.map(w=><li key={w}>{w}</li>):<li>None</li>}</ul></section><section className="card p-5"><h2 className="font-semibold">Mastered</h2><ul className="mt-2 list-disc pl-5 text-sm">{strong.length?strong.map(w=><li key={w}>{w}</li>):<li>None yet</li>}</ul></section></div>
 <section className="card mt-4 p-5"><h2 className="font-semibold">Recommended next steps</h2><p className="mt-1 text-sm text-slate-600">{weak.length?`Your performance suggests revisiting ${weak[0].toLowerCase()} before attempting more advanced problems.`:'Strong result. Move on to the next concept in your learning path.'}</p></section>
 <div className="mt-4 flex gap-2"><Button to="/student/learning-path">Continue learning</Button><Button to="/student/gaps" variant="ghost">View learning gaps</Button></div></div>}
