import {useEffect,useState} from 'react';import {Link,useParams,useNavigate} from 'react-router-dom';
import {LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from 'recharts';
import {Users,AlertTriangle,Gauge,Brain,Search,Upload,FileText,Download,Check,X,Loader2} from 'lucide-react';
import {StatCard,PageHead,Button,ChartCard,RiskBadge,SeverityBadge,ProgressBar,EmptyState} from '../components/ui';
import {classTrend,classGaps,distribution,trend,quizScores,recentActivity,classKpis} from '../data/analytics';import {materials as seed,conceptOptions} from '../data/materials';import {ConfirmDialog} from '../components/ui';import {students,aiGaps} from '../data/students';
import {api} from '../api';
const Trend=()=><ChartCard title="Class performance" sub="Average competency %"><LineChart data={classTrend}><CartesianGrid stroke="#E3E6EC" vertical={false}/><XAxis dataKey="w"/><YAxis domain={[40,100]}/><Tooltip/><Line dataKey="v" name="Average" stroke="#2F4FA8" strokeWidth={3}/></LineChart></ChartCard>;
const Dist=()=><ChartCard title="Concept mastery distribution" sub="Students per mastery band"><BarChart data={distribution}><XAxis dataKey="r"/><YAxis/><Tooltip/><Bar dataKey="n" name="Students" fill="#2F4FA8" radius={6}/></BarChart></ChartCard>;
function Table({rows}){const go=useNavigate();return <div className="card overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-line text-slate-500"><tr>{['Student','Competency','Learning gaps','Status','Last active'].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead>
 <tbody>{rows.map(s=><tr key={s.id} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&go(`/teacher/students/${s.id}`)} onClick={()=>go(`/teacher/students/${s.id}`)} className="cursor-pointer border-b border-line last:border-0 hover:bg-brand-50"><td className="p-3 font-medium">{s.name}</td><td className="p-3">{s.competency}%</td><td className="p-3">{Math.round(s.competency/4)}</td><td className="p-3">{s.gaps}</td><td className="p-3"><RiskBadge level={s.risk}/></td><td className="p-3 text-slate-500">{s.last}</td></tr>)}</tbody></table></div>}

function DemoTeacherStudents(){const [q,setQ]=useState('');const [risk,setRisk]=useState('All');const [sort,setSort]=useState('name');const [pg,setPg]=useState(0);const go=useNavigate();
 let rows=students.filter(s=>s.name.toLowerCase().includes(q.toLowerCase())&&(risk==='All'||s.risk===risk));rows=[...rows].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):a.competency-b.competency);const per=6,pages=Math.max(1,Math.ceil(rows.length/per)),vis=rows.slice(pg*per,pg*per+per);
 const sel='rounded-xl border border-line bg-white px-3 py-2 text-sm';
 return <><PageHead title="Students"/><div className="mb-4 flex flex-wrap gap-3"><label className="relative flex-1 min-w-[200px]"><span className="sr-only">Search students</span><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>{setQ(e.target.value);setPg(0)}} placeholder="Search students" className={`${sel} w-full pl-9`}/></label>
 <select aria-label="Filter by risk" className={sel} value={risk} onChange={e=>{setRisk(e.target.value);setPg(0)}}>{['All','High','Medium','Low'].map(r=><option key={r}>{r}</option>)}</select>
 <select aria-label="Sort" className={sel} value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Sort: Name</option><option value="comp">Sort: Competency</option></select></div>
 {vis.length?<div className="card overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-line text-slate-500"><tr>{['Student','Competency','Mastered','Gaps','Status','Last active','Progress','Action'].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{vis.map(s=><tr key={s.id} className="border-b border-line last:border-0"><td className="p-3 font-medium">{s.name}</td><td className="p-3">{s.competency}%</td><td className="p-3">{Math.round(s.competency/4)}</td><td className="p-3">{s.gaps}</td><td className="p-3"><RiskBadge level={s.risk}/></td><td className="p-3 text-slate-500">{s.last}</td><td className={`p-3 font-semibold ${s.progress<0?'text-bad':'text-good'}`}>{s.progress>0?'+':''}{s.progress}%</td><td className="p-3"><Button variant="ghost" onClick={()=>go(`/teacher/students/${s.id}`)}>View student</Button></td></tr>)}</tbody></table></div>:<EmptyState text="No students match your filters."/>}
 <div className="mt-4 flex items-center justify-end gap-3 text-sm"><Button variant="ghost" disabled={pg===0} onClick={()=>setPg(pg-1)}>Previous</Button>Page {pg+1} of {pages}<Button variant="ghost" disabled={pg+1>=pages} onClick={()=>setPg(pg+1)}>Next</Button></div></>}




const Perf=()=><ChartCard title="Student performance" sub="Competency % by student"><BarChart data={students}><XAxis dataKey="name" tickFormatter={n=>n.split(' ')[0]}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="competency" fill="#2F4FA8" radius={6}/></BarChart></ChartCard>;
const Common=()=><ChartCard title="Most common learning gaps" sub="Students affected"><BarChart data={classGaps}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="students" fill="#B45309" radius={6}/></BarChart></ChartCard>;
export function TeacherHome(){return <><PageHead title="Good morning, Professor" sub="Here’s how your class is progressing."/>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Total students" value={classKpis.students} icon={Users}/><StatCard label="Average competency" value={`${classKpis.competency}%`} icon={Gauge}/><StatCard label="Students with gaps" value={classKpis.withGaps} icon={AlertTriangle}/><StatCard label="Gaps resolved" value={classKpis.resolved} icon={Check}/></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-2"><Trend/><Dist/><Common/><Perf/></div>
 <h2 className="mb-3 mt-8 font-display text-xl">Students requiring attention</h2><Table rows={students.filter(s=>s.risk!=='Low').slice(0,6)}/></>}
export function StudentAnalysis(){const {id}=useParams();const s=students.find(x=>x.id===id);const [dec,setDec]=useState({});const [toast,setToast]=useState('');const [ask,setAsk]=useState(null);
 if(!s)return <EmptyState text="Student not found."/>;
 const decide=(g,v)=>{setDec({...dec,[g.id]:v});setAsk(null);setToast(v==='ok'?'Gap confirmed successfully.':'Gap rejected.');setTimeout(()=>setToast(''),3500)};
 return <><PageHead title={s.name} sub="Student overview and AI gap analysis"><RiskBadge level={s.risk}/></PageHead>
 <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Overall competency" value={`${s.competency}%`}/><StatCard label="Mastered concepts" value={Math.round(s.competency/4)}/><StatCard label="Learning gaps" value={s.gaps}/></div>
 <div className="mt-6 grid gap-4 lg:grid-cols-2"><ChartCard title="Competency trend"><LineChart data={trend}><XAxis dataKey="w"/><YAxis domain={[30,100]}/><Tooltip/><Line dataKey="v" stroke="#2F4FA8" strokeWidth={3}/></LineChart></ChartCard><ChartCard title="Quiz performance"><BarChart data={quizScores}><XAxis dataKey="q"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="v" fill="#0F7B53" radius={6}/></BarChart></ChartCard>
 <section className="card p-5"><h3 className="font-semibold">Concept mastery</h3><div className="mt-4 space-y-3 text-sm">{[['Variables and types',90],['Conditions',70],['Python functions',Math.max(10,s.competency-10)],['Loops',s.competency]].map(([n,v])=><div key={n}><div className="flex justify-between"><span>{n}</span><span>{v}%</span></div><ProgressBar value={v}/></div>)}</div></section>
 <section className="card p-5"><h3 className="font-semibold">Recent activity</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{recentActivity.map(a=><li key={a}>{a}</li>)}</ul></section></div>
 <h2 className="mb-3 mt-8 font-display text-xl">AI gap analysis</h2><div className="space-y-4">{aiGaps.map(g=><article key={g.id} className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{g.concept}</h3><span className="flex items-center gap-3 text-sm"><SeverityBadge level={g.severity}/>Mastery <b>{g.mastery}%</b> · Confidence <b>{g.confidence}%</b></span></div>
 <dl className="mt-3 space-y-1 text-sm">{[['Reason',g.reason],['Evidence',g.evidence],['Prerequisite gap',g.prereq],['Recommendation',g.intervention]].map(([k,v])=><div key={k}><dt className="inline font-semibold">{k}: </dt><dd className="inline">{v}</dd></div>)}</dl>
 <div className="mt-4 flex flex-wrap items-center gap-2">{dec[g.id]?<span className={`flex items-center gap-1 text-sm font-semibold ${dec[g.id]==='ok'?'text-good':'text-bad'}`}>{dec[g.id]==='ok'?<><Check size={16}/>Confirmed by teacher</>:<><X size={16}/>Rejected by teacher</>}</span>:<><Button variant="good" onClick={()=>decide(g,'ok')}>Confirm gap</Button><Button variant="bad" onClick={()=>setAsk(g)}>Reject gap</Button></>}</div></article>)}</div>
 <ConfirmDialog open={!!ask} title={`Reject gap: ${ask?.concept}?`} text="The system will treat this detection as incorrect." onConfirm={()=>decide(ask,'no')} onCancel={()=>setAsk(null)}/>
 {toast&&<div role="status" className="fixed bottom-4 left-1/2 z-50 w-[90%] max-w-md -translate-x-1/2 rounded-xl bg-ink px-4 py-3 text-sm text-white shadow-lg">{toast}</div>}</>}
export function TeacherGaps(){return <><PageHead title="Class Learning Gaps" sub="Concepts where many students struggle."/><div className="card overflow-x-auto"><table className="w-full min-w-[480px] text-left text-sm"><thead className="border-b border-line text-slate-500"><tr>{['Concept','Students affected','Avg mastery','Severity'].map(h=><th key={h} className="p-3 font-medium">{h}</th>)}</tr></thead><tbody>{classGaps.map(g=><tr key={g.name} className="border-b border-line last:border-0"><td className="p-3 font-medium">{g.name}</td><td className="p-3">{g.students}</td><td className="p-3">{g.mastery}%</td><td className="p-3"><SeverityBadge level={g.severity}/></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Common/><Dist/></div></>}
export function Materials(){const [list,setList]=useState(seed);const [f,setF]=useState({title:'',concept:conceptOptions[0],difficulty:'Medium',desc:'',file:null});const [err,setErr]=useState('');const [msg,setMsg]=useState('');
 const submit=e=>{e.preventDefault();if(!f.title.trim()||!f.file){setErr('Add a title and choose a file.');return}setErr('');const n=f.file.name;setList([{n,title:f.title,concept:f.concept,difficulty:f.difficulty,desc:f.desc,t:'Just now',s:'Processing'},...list]);setTimeout(()=>setList(l=>l.map(x=>x.n===n?{...x,s:'Processed'}:x)),2000);setF({...f,title:'',desc:'',file:null});e.target.reset()};
 const inp='mt-1 w-full rounded-xl border border-line bg-white px-3 py-2 text-sm';
 return <><PageHead title="Study Materials" sub="Upload notes to link them with concepts and generate quizzes."/>
 <form onSubmit={submit} className="card grid gap-4 p-5 sm:grid-cols-2"><label className="text-sm font-medium">Title<input className={inp} value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label>
 <label className="text-sm font-medium">File (PDF, DOCX, PPTX)<input type="file" accept=".pdf,.docx,.pptx" className={inp} onChange={e=>setF({...f,file:e.target.files[0]})}/></label>
 <label className="text-sm font-medium">Concept<select className={inp} value={f.concept} onChange={e=>setF({...f,concept:e.target.value})}>{conceptOptions.map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="text-sm font-medium">Difficulty<select className={inp} value={f.difficulty} onChange={e=>setF({...f,difficulty:e.target.value})}>{['Easy','Medium','Hard'].map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="text-sm font-medium sm:col-span-2">Description<textarea rows={2} className={inp} value={f.desc} onChange={e=>setF({...f,desc:e.target.value})}/></label>
 <div className="flex items-center gap-3 sm:col-span-2"><Button type="submit"><Upload size={16}/>Upload material</Button>{err&&<span role="alert" className="text-sm text-bad">{err}</span>}</div></form>
 {list.length?<ul className="mt-6 space-y-3">{list.map(m=><li key={m.n} className="card flex flex-wrap items-center justify-between gap-3 p-4"><span className="flex items-center gap-3"><FileText className="text-brand-600"/><span><b className="block text-sm">{m.title}</b><span className="text-xs text-slate-500">{m.n} · {m.concept} · {m.difficulty} · {m.t}</span></span></span>
 <span className="flex items-center gap-3 text-sm">{m.s==='Processing'?<span className="flex items-center gap-1 text-warn"><Loader2 size={14} className="animate-spin"/>Processing</span>:<span className="text-good">Processed</span>}<Button disabled={m.s!=='Processed'} onClick={()=>setMsg(`Quiz generated from ${m.title}: 10 questions on ${m.concept}.`)}>Generate quiz</Button></span></li>)}</ul>:<div className="mt-6"><EmptyState text="No materials uploaded yet."/></div>}{msg&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-good">{msg}</p>}</>}
export function Reports(){const [m,setM]=useState(false);
 const exp=()=>{const rows=[['Student','Competency','Gaps','Status'],...students.map(s=>[s.name,s.competency,s.gaps,s.risk])];const b=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='class-report.csv';a.click();setM(true);setTimeout(()=>setM(false),2500)};
 return <><PageHead title="Reports" sub="Class overview for this term."><Button onClick={exp}><Download size={16}/>Export report</Button></PageHead>{m&&<p role="status" className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-good">Report downloaded as class-report.csv.</p>}
 <div className="mb-4 grid grid-cols-2 gap-4 lg:grid-cols-4"><StatCard label="Class competency" value={`${classKpis.competency}%`}/><StatCard label="Students with gaps" value={classKpis.withGaps}/><StatCard label="Gaps resolved" value={classKpis.resolved}/><StatCard label="Resolution rate" value="36%" hint="resolved / detected"/></div>
 <div className="grid gap-4 lg:grid-cols-2"><Trend/><Dist/><Common/><Perf/></div></>}

export function TeacherAssessments(){
 const [title,setTitle]=useState('Python Fundamentals: Explain a Function');
 const [description,setDescription]=useState('Explain how Python functions help organize reusable code.');
 const [question,setQuestion]=useState('What is a function in Python, and how do parameters and return values help it work?');
 const [conceptLines,setConceptLines]=useState('Function|reusable block, def\nParameter|input, argument\nReturn value|return, output');
 const [subject,setSubject]=useState('Python Fundamentals');
 const [items,setItems]=useState([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [submissions,setSubmissions]=useState({});
 async function refresh(){try{const data=await api('/assessments');setItems(data.assessments||[])}catch(e){setError(e.message)}}
 useEffect(()=>{refresh()},[]);
 async function create(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{
   const expected_concepts=conceptLines.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [name,...words]=line.split('|');return{name:name.trim(),keywords:words.join('|').split(',').map(x=>x.trim()).filter(Boolean)}});
   await api('/assessments',{method:'POST',body:JSON.stringify({title,description,question,subject,expected_concepts})});
   setMessage('Assessment saved to MongoDB. Students can now see it.');await refresh();
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 async function showSubmissions(id){setError('');try{const data=await api(`/assessments/${id}/submissions`);setSubmissions({...submissions,[id]:data.submissions||[]})}catch(e){setError(e.message)}}
 const input='mt-1 w-full rounded-xl border border-line bg-white px-3 py-2 text-sm';
 return <><PageHead title="Python Assessments" sub="Create a question and store its expected concepts in MongoDB."/>
 <form onSubmit={create} className="card grid gap-4 p-5"><label className="text-sm font-medium">Subject<select className={input} value={subject} onChange={e=>setSubject(e.target.value)}>{subjectOptions.map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm font-medium">Assessment title<input required minLength={3} className={input} value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label className="text-sm font-medium">Description<input className={input} value={description} onChange={e=>setDescription(e.target.value)}/></label>
 <label className="text-sm font-medium">Written question<textarea required minLength={10} rows={3} className={input} value={question} onChange={e=>setQuestion(e.target.value)}/></label>
 <label className="text-sm font-medium">Expected concepts (one per line: concept|keyword, keyword)<textarea required rows={4} className={input} value={conceptLines} onChange={e=>setConceptLines(e.target.value)}/></label>
 <p className="text-xs text-slate-500">These expected concepts stay teacher-side and are used by the backend analyzer.</p>
 <div className="flex flex-wrap items-center gap-3"><Button type="submit" disabled={busy}>{busy?'Saving…':'Create assessment'}</Button>{message&&<span role="status" className="text-sm text-good">{message}</span>}</div>
 {error&&<p role="alert" className="text-sm text-bad">{error}</p>}</form>
 <h2 className="mb-3 mt-8 font-display text-xl">Saved assessments</h2>{items.length?<div className="space-y-3">{items.map(a=><article key={a.assessment_id} className="card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-brand-600">{a.subject}</p><h3 className="mt-1 font-semibold">{a.title}</h3><p className="mt-1 text-sm text-slate-500">{a.question}</p></div><Button variant="ghost" onClick={()=>showSubmissions(a.assessment_id)}>View student submissions</Button></div>{submissions[a.assessment_id]&&<div className="mt-4 space-y-3">{submissions[a.assessment_id].length?submissions[a.assessment_id].map(s=><div key={s.submission_id} className="rounded-xl bg-paper p-4 text-sm"><div className="flex justify-between gap-2"><b>{s.student_name}</b><b>{s.coverage_percent}% coverage</b></div><p className="mt-2">{s.answer}</p><p className="mt-2 text-slate-600">Shown: {s.matched_concepts.join(', ')||'none'} · Possible gaps: {s.possible_gaps.join(', ')||'none'}</p></div>):<p className="text-sm text-slate-500">No student submissions yet.</p>}</div>}</article>)}</div>:<EmptyState text="No assessments have been saved yet."/>}</>}

const subjectOptions=['Python Fundamentals','Python Variables and Types','Python Conditions and Loops','Python Functions','Python Lists and Dictionaries'];

export function TeacherStudents(){
 const [email,setEmail]=useState('');const [subject,setSubject]=useState(subjectOptions[0]);const [assignments,setAssignments]=useState([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 async function refresh(){try{const data=await api('/teacher/assignments');setAssignments(data.assignments||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 async function assign(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const data=await api('/teacher/assignments',{method:'POST',body:JSON.stringify({student_email:email,subject})});setNotice(data.status==='pending'?'Assignment saved. When the student signs up using this email, the subject will appear in their account.':'Student assigned to this subject.');setEmail('');await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const input='mt-1 w-full rounded-xl border border-line bg-white px-3 py-2.5 text-sm';
 return <><PageHead title="My Students" sub="Assign students by email and follow their assessment progress."/>
 <form onSubmit={assign} className="card grid gap-4 p-5 md:grid-cols-[1fr_1fr_auto] md:items-end"><label className="text-sm font-medium">Student email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="student@example.com" className={input}/></label><label className="text-sm font-medium">Subject<select value={subject} onChange={e=>setSubject(e.target.value)} className={input}>{subjectOptions.map(item=><option key={item}>{item}</option>)}</select></label><Button type="submit" disabled={busy}>{busy?'Assigning…':'Add student'}</Button><p className="text-xs text-slate-500 md:col-span-3">If the student has not signed up yet, the assignment waits for them to register with this same email.</p></form>
 {error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-bad">{error}</p>}{notice&&<p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-good">{notice}</p>}
 <h2 className="mb-3 mt-8 font-display text-xl">Assigned students and progress</h2>
 {loading?<EmptyState text="Loading assigned students…"/>:assignments.length?<div className="card overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-line text-slate-500"><tr>{['Student','Subject','Account','Assessments','Submitted','Average coverage','Recent activity'].map(label=><th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{assignments.map(item=><tr key={item.assignment_id} className="border-b border-line last:border-0"><td className="p-3"><b className="block">{item.student_name||'Awaiting sign-up'}</b><span className="text-xs text-slate-500">{item.student_email}</span></td><td className="p-3">{item.subject}</td><td className="p-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status==='active'?'bg-emerald-50 text-good':'bg-amber-50 text-warn'}`}>{item.status==='active'?'Active':'Pending'}</span></td><td className="p-3">{item.assessment_count}</td><td className="p-3">{item.submission_count}</td><td className="p-3">{item.progress_percent}%</td><td className="p-3 text-slate-500">{item.last_activity?new Date(item.last_activity).toLocaleDateString():'No submissions yet'}</td></tr>)}</tbody></table></div>:<EmptyState text="No assigned students yet. Add a student email above."/>}</>
}
